spring:
  datasource:
    url: jdbc:mysql://172.31.37.190:30000/transaction?serverTimezone=UTC&characterEncoding=UTF-8
    username: ks
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: trace

